{% set name = "magika" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/magika-{{ version }}.tar.gz
  sha256: e3dd22c73936630b1cd79d0f412d6d9a53dc99ba5e3709b1ac53f56bc998e635

build:
  entry_points:
    - magika = magika.cli.magika:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0,<3.12
    - click >=8.1.3,<9.0.0
    - tqdm >=4.64.1,<5.0.0
    - onnxruntime >=1.15.1,<2.0.0
    - numpy >=1.24.4,<2.0.0
    - tabulate >=0.9.0,<0.10.0
    - python-dotenv >=1.0.1,<2.0.0

test:
  imports:
    - magika
  commands:
    - pip check
    - magika --help
  requires:
    - pip

about:
  home: https://github.com/google/magika
  dev_url: https://github.com/google/magika/tree/main/python
  doc_url: https://github.com/google/magika
  summary: A tool to determine the content type of a file with deep-learning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
