{% set name = "magika" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/magika-{{ version }}.tar.gz
  sha256: e3dd22c73936630b1cd79d0f412d6d9a53dc99ba5e3709b1ac53f56bc998e635

build:
  entry_points:
    - magika = magika.cli.magika:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - onnxruntime >=1.17.0
    - numpy >=1.24
    - python-dotenv >=1.0.1

test:
  imports:
    - magika
  commands:
    - pip check
    - magika --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/magika
  dev_url: https://github.com/google/magika/tree/main/python
  doc_url: https://github.com/google/magika
  summary: A tool to determine the content type of a file with deep-learning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
